### ISSUE TITLE
Plz Help, Error compiling for board sanguino

### ISSUE THREAD

**Issue by MappM** [eloquentarduino/EloquentArduino#13]
Im attempting to Add BL TOUCH to my CR10 Mini by updating with Marlin 2.0, First thing i did was use ELEGOO controller board to add boot loader. I believe this was successful because my CR10 Mini turned on afterwards and it displayed Marlin at start up. I noticed it had more options inside display. The step that i am stuck on is getting this message
In file included from sketch/src/HAL/AVR/../../inc/MarlinConfig.h:28:0,
                 from sketch/src/HAL/AVR/HAL 2.cpp:24:
sketch/src/HAL/AVR/../../inc/MarlinConfigPre.h:39:10: fatal error: ../../Configuration.h: No such file or directory
 #include "../../Configuration.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Sanguino.

**Comment by eloquentarduino** [comment]
Are you sure you commented on the right repository? This repo is not about Marlin.
