### ISSUE TITLE
In the Apple vs Orange code, is it possible to not average the image size and use the original (160x120) size?

### ISSUE THREAD

**Issue by rahullabs** [eloquentarduino/EloquentArduino#14]
Thanks for the code but is it possible to use the original size of the image instead of averaged out by block?

**Comment by eloquentarduino** [comment]
Although *technically* possible, I cannot see why you would so such a thing, if not using neural networks. Any classifier fed by 160*120 = 19200 features would only get confused.
Moreover, images from the camera suffer from a high degree of noise, so you are **strongly** recommended to filter that noise out: averaging is one of the possible methods.
