### ISSUE TITLE
the motion detect when turned the light on and off 

### ISSUE THREAD

**Issue by endermaxximum** [eloquentarduino/EloquentArduino#19]
How can I set the sensitivity of the motion detect?
Because when I only turned the light off the camera was detected the motion (this happened with turned light on also).

**Comment by eloquentarduino** [comment]
"Motion detection" is actually a bit misleading as name. The library detects any substantial change in the pixels' values: when you turn the light off, all the pixels go from light to almost black, so "motion" is detected (the same when you turn the light on).
It is intended behavior, and you cannot set any sensitivity to change this.
What you can try to do, instead, is putting an upper threshold on the detector `ratio()`: if it is too high (> 90% for example), don't trigger the motion detection.

**Comment by endermaxximum** [comment]
thank you
