### ISSUE TITLE
classIdxToName never returns default state in switch

### ISSUE THREAD

**Issue by manolisstam** [eloquentarduino/EloquentArduino#6]
Hello again, and another time congrats for your awsome ideas and works.
i/ve seen and recreate the iris and word classifications, everything is ok, BUT i never get the default switch case.
For example if i type random numbers (in iris classification ) in serial monitor i always get a prediction. 
Why is that ?
Thanx  again for your time

**Comment by eloquentarduino** [comment]
What you call "random numbers" are nevertheless considered as features: there is not a "default switch case".
A classifier (all of them, not only this implemented here) will always output a class if you give it an input: it can't distinguish "real" vs "random" data.

**Comment by manolisstam** [comment]
thank you, once again for your answer
